#%RAML 1.0 Trait

queryParameters:
  systemCat:
    type: string
    required: true
    example: genericGps
  catalogName:
    type: string
    required: true
    example: nombreProveedores
  key_search:
    type: string
    required: true
    example: EGOBA
  value_result:
    type: string
    required: true
    example: EGB_234