#%RAML 1.0 Trait

headers:
  client_id:
    type: string
    example: alksd82938-asdf23-ase23ew
  client_secret:
    type: string
    example: askedufhaks-asdfasqswer-asdwqedwas  
responses:
  401:
    description: Unauthorized or invalid client application credentials
  500:
    description: Bad response from authorization server, or WSDL SOAP Fault errorheaders